"""init db

迁移 ID: 7844a03326d1
父迁移: 
创建时间: 2024-08-19 17:56:20.623440

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7844a03326d1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('ban_image',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_image_groupimagebaninfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('img_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ban_image_groupimagebaninfo')),
    info={'bind_key': 'ban_image'}
    )
    with op.batch_alter_table('ban_image_groupimagebaninfo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_image_groupimagebaninfo_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ban_image_groupimagebaninfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_image_groupimagebaninfo_group_id'))

    op.drop_table('ban_image_groupimagebaninfo')
    # ### end Alembic commands ###
