"""add index

迁移 ID: 578a2ee2cb89
父迁移: 
创建时间: 2024-07-27 10:34:08.449106

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '578a2ee2cb89'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('ban_image',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ban_image_groupimagebaninfo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ban_image_groupimagebaninfo_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ban_image_groupimagebaninfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ban_image_groupimagebaninfo_group_id'))

    # ### end Alembic commands ###
