"""add mime type column

迁移 ID: 02b84c026502
父迁移: b12db5a4353d
创建时间: 2025-06-26 11:57:08.865544

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '02b84c026502'
down_revision: str | Sequence[str] | None = 'b12db5a4353d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.drop_column('mime_type')
    # ### end Alembic commands ###
