"""add EmojiInfoStorer table

迁移 ID: 0cd27cbc283a
父迁移: 65bfa681bf23
创建时间: 2025-06-20 23:21:47.877432

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0cd27cbc283a'
down_revision: str | Sequence[str] | None = '65bfa681bf23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_like_emojiinfostorer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people_like_emojiinfostorer')),
    info={'bind_key': 'people_like'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_like_emojiinfostorer')
    # ### end Alembic commands ###
