"""add remote_file_name cloumn

迁移 ID: 65bfa681bf23
父迁移: ae735f870da6
创建时间: 2025-06-05 18:41:13.330306

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '65bfa681bf23'
down_revision: str | Sequence[str] | None = 'ae735f870da6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_file_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.drop_column('remote_file_name')

    # ### end Alembic commands ###
