"""init db

迁移 ID: 697b8ef25748
父迁移: 
创建时间: 2025-04-12 17:02:34.788266

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '697b8ef25748'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('people_like',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_like_imagesender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ext_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_uri', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('emoji_id', sa.String(), nullable=True),
    sa.Column('emoji_package_id', sa.String(), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people_like_imagesender')),
    info={'bind_key': 'people_like'}
    )
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_like_imagesender_name'), ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_like_imagesender_name'))

    op.drop_table('people_like_imagesender')
    # ### end Alembic commands ###
