"""add summary column

迁移 ID: ae735f870da6
父迁移: 697b8ef25748
创建时间: 2025-04-14 20:15:20.128766

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ae735f870da6'
down_revision: str | Sequence[str] | None = '697b8ef25748'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
