"""remove fileuri remotefilename

迁移 ID: dca2bd08f07e
父迁移: 50ff9b8e6fac
创建时间: 2025-07-29 16:41:12.795380

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dca2bd08f07e'
down_revision: str | Sequence[str] | None = '50ff9b8e6fac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.drop_column('file_uri')
        batch_op.drop_column('remote_file_name')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_imagesender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_file_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('file_uri', sa.VARCHAR(), nullable=False, default=""))

    # ### end Alembic commands ###
