"""set message_id nullable

迁移 ID: f93a7ac102cd
父迁移: 50ff9b8e6fac
创建时间: 2025-08-19 10:43:24.645185

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f93a7ac102cd'
down_revision: str | Sequence[str] | None = '50ff9b8e6fac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

 
def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_groupmsg', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_like_groupmsg', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
