# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ssh sparse deploy 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'forward_plugins/**'
      - 'direct_plugins/**'
      - 'common/**'
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'forward_plugins/**'
      - 'direct_plugins/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v46

    - name: generate scp upload command
      id: scp-cmd
      run: |
        echo "SCP_FILES=" > scp_files.env
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ "$file" == forward_plugins/* ]]; then
            echo "'$file' => ~/forward/src/plugins/$(basename $(dirname "$file"))" >> scp_files.env
          elif [[ "$file" == direct_plugins/* ]]; then
            echo "'$file' => ~/direct/src/plugins/$(basename $(dirname "$file"))" >> scp_files.env
          elif [[ "$file" == common/* ]]; then
            echo "'$file' => ~/forward/common" >> scp_files.env
            echo "'$file' => ~/direct/common" >> scp_files.env
          fi
        done
        echo "SCP_FILES<<EOF" > $GITHUB_ENV
        cat scp_files.env >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      if: ${{ ! endsWith(env.SCP_FILES, 'SCP_FILES=') }}
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_KEY }}
        first_ssh: |
          kill $(cat ~/forward/pid) || true
          kill $(cat ~/direct/pid) || true
        scp: ${{ env.SCP_FILES }}
        last_ssh: |
          cd ~/forward
          source ~/forward/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/.local/bin/nb run >> ~/forward/logs/forward.log 2>&1 & echo $! > ~/forward/pid;
          cd ~/direct
          source ~/direct/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/.local/bin/nb run >> ~/direct/logs/direct.log 2>&1 & echo $! > ~/direct/pid;
          # 检查端口是否有进程监听
          sleep 10
          if pgrep -f $(cat ~/forward/pid) > /dev/null; then
              echo "进程 forward 正在运行"
          else
              echo "进程 forward 不存在"
          fi
          if pgrep -f $(cat ~/direct/pid) > /dev/null; then
              echo "进程 direct 正在运行"
          else
              echo "进程 direct 不存在"
          fi