# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ssh deploy
run-name: ssh deploy ${{ inputs.commit && format('commit {0}', inputs.commit) || '' }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA to deploy (leave empty for latest)'
        required: false
        type: string
        default: ''


jobs:
  scp:
    name: scp files to remote
    uses: ./.github/workflows/python-runner.yml
    secrets:
      host: ${{ secrets.DC_HOST }}
      user: ${{ secrets.DC_USER }}
      key: ${{ secrets.DC_KEY }}
    with:
      ref: ${{ inputs.commit || github.sha }}
      pre_ssh: |
        kill $(cat ~/forward/pid) || true
        kill $(cat ~/direct/pid) || true
        rm -rf ~/forward/src/plugins
        rm -rf ~/direct/src/plugins
      scp: |
        './forward_plugins/*' => ~/forward/src/plugins
        './common/*' => ~/forward/common
        './direct_plugins/*' => ~/direct/src/plugins
        './common/*' => ~/direct/common
      post_ssh: |
        cd ~/forward
        source ~/forward/.venv/bin/activate
        nohup ~/.local/bin/nb orm upgrade
        nohup ~/forward/.venv/bin/python3 bot.py >> ~/forward/logs/forward.log 2>&1 & echo $! > ~/forward/pid;
        cd ~/direct
        source ~/direct/.venv/bin/activate
        nohup ~/.local/bin/nb orm upgrade
        nohup ~/direct/.venv/bin/python3 bot.py >> ~/direct/logs/direct.log 2>&1 & echo $! > ~/direct/pid;
