# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ssh sparse deploy 

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44

    - name: generate scp upload command
      id: scp-cmd
      run: |
        echo "SCP_FILES=" > scp_files.env
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # 只处理 forward_plugins、direct_plugins、common 目录下的文件
          if [[ "$file" == forward_plugins/* ]]; then
            echo "'$file' => ~/forward/src/plugins/$(basename $file)" >> scp_files.env
          elif [[ "$file" == direct_plugins/* ]]; then
            echo "'$file' => ~/direct/src/plugins/$(basename $file)" >> scp_files.env
          elif [[ "$file" == common/* ]]; then
            echo "'$file' => ~/forward/common/$(basename $file)" >> scp_files.env
            echo "'$file' => ~/direct/common/$(basename $file)" >> scp_files.env
          fi
        done
        echo "SCP_FILES<<EOF" > $GITHUB_ENV
        cat scp_files.env >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      if: ${{ ! endsWith(env.SCP_FILES, 'SCP_FILES=') }}
      env:
        PORT_FORWARD: ${{ secrets.FORWARD_PORT }}
        PORT_DIRECT: ${{ secrets.DIRECT_PORT }}
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_KEY }}
        first_ssh: |
          bash ~/kill_process.sh $PORT_FORWARD
          bash ~/kill_process.sh $PORT_DIRECT
        scp: ${{ env.SCP_FILES }}
        last_ssh: |
          cd ~/forward
          source ~/forward/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/.local/bin/nb run >> ~/forward/forward.log 2>&1 &;
          cd ~/direct
          source ~/direct/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/.local/bin/nb run >> ~/direct/direct.log 2>&1 &;