# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ssh deploy 

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA to deploy (leave empty for latest)'
        required: false
        type: string
        default: ''


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commit || github.sha }}
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        PORT_FORWARD: ${{ secrets.FORWARD_PORT }}
        PORT_DIRECT: ${{ secrets.DIRECT_PORT }}
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_KEY }}
        first_ssh: |
          bash ~/kill_process.sh $PORT_FORWARD
          bash ~/kill_process.sh $PORT_DIRECT
          rm -rf ~/forward/src/plugins
          rm -rf ~/direct/src/plugins
        scp: |
          './forward_plugins/*' => ~/forward/src/plugins
          './common/*' => ~/forward/common
          './direct_plugins/*' => ~/direct/src/plugins
          './common/*' => ~/direct/common
        last_ssh: |
          cd ~/forward
          source ~/forward/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/forward/.venv/bin/python3 bot.py >> ~/forward/logs/forward.log 2>&1 &;
          cd ~/direct
          source ~/direct/.venv/bin/activate
          nohup ~/.local/bin/nb orm upgrade
          nohup ~/direct/.venv/bin/python3 bot.py >> ~/direct/logs/direct.log 2>&1 &;
          # 检查端口是否有进程监听
          sleep 10
          if ! lsof -i :$PORT_FORWARD | grep LISTEN; then
            echo "Error: forward 端口 $PORT_FORWARD 没有进程监听"
            exit 1
          fi
          if ! lsof -i :$PORT_DIRECT | grep LISTEN; then
            echo "Error: direct 端口 $PORT_DIRECT 没有进程监听"
            exit 1
          fi